# Generated by Django 4.2.20 on 2025-03-23 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("business_suppliers", "0002_suppliertransaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suppliertransaction",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
