# Generated by Django 4.2.20 on 2025-03-20 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finances", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="account",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="account",
            name="slug",
            field=models.SlugField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="account",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="my_accounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="my_categories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="account",
            unique_together={("owner", "slug")},
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("owner", "slug")},
        ),
    ]
