# Generated by Django 4.2.20 on 2025-03-23 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("business_suppliers", "0001_initial"),
        ("finances", "0003_supplier_suppliertransaction"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="suppliertransaction",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="suppliertransaction",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="suppliertransaction",
            name="supplier",
        ),
        migrations.RemoveField(
            model_name="suppliertransaction",
            name="transaction",
        ),
        migrations.AddField(
            model_name="transaction",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="business_suppliers.supplier",
            ),
        ),
        migrations.DeleteModel(
            name="Supplier",
        ),
        migrations.DeleteModel(
            name="SupplierTransaction",
        ),
    ]
