# Generated by Django 4.2.20 on 2025-03-23 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0004_alter_suppliertransaction_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="supplier",
        ),
    ]
