# Generated by Django 4.2.30 on 2026-09-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "finances",
            "0008_alter_transactionimport_status_transactionimportitem_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionimport",
            name="report_email_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="transactionimport",
            name="report_email_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="transactionimport",
            name="report_email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transactionimport",
            name="report_email_status",
            field=models.CharField(
                choices=[
                    ("NOT_SCHEDULED", "Not scheduled"),
                    ("SCHEDULED", "Scheduled"),
                    ("SENDING", "Sending"),
                    ("SENT", "Sent"),
                    ("SKIPPED", "Skipped"),
                    ("FAILED", "Failed"),
                ],
                default="NOT_SCHEDULED",
                max_length=20,
            ),
        ),
    ]
