# Generated by Django 4.2.30 on 2026-09-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "finances",
            "0009_transactionimport_report_email_attempts_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionimport",
            name="report_email_message_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="transactionimport",
            name="report_email_provider",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
